Repository crossplane-contrib/provider-upjet-gcp, pull requests merged in 2022-10, with the labels that each got.

#30 Add contribution guides and badges
  README.md
Labels: size/M

#31 Downgrade go version to 1.18
  .github/workflows/ci.yml
  .github/workflows/uptest-all.yml
  .github/workflows/uptest.yml
  Makefile
  go.mod
Labels: size/XS

#32 Bump Go version to v1.19
  .github/workflows/ci.yml
  .github/workflows/uptest-all.yml
  .github/workflows/uptest.yml
  Makefile
  apis/compute/v1beta1/zz_firewallpolicyrule_types.go
  apis/compute/v1beta1/zz_projectmetadataitem_types.go
  apis/notebooks/v1beta1/zz_runtime_types.go
  config/compute/config.go
  config/notebooks/config.go
  go.mod
  package/crds/compute.gcp.upbound.io_firewallpolicyrules.yaml
  package/crds/compute.gcp.upbound.io_projectmetadataitems.yaml
  package/crds/notebooks.gcp.upbound.io_runtimes.yaml
Labels: size/M

#33 Add a section about workload identity to configuration.md
  docs/Configuration.md
  examples/providerconfig/workloadidentity.yaml
Labels: size/L, backport release-0.16

#36 Bump Go version to v1.19
  apis/compute/v1beta1/zz_firewallpolicyrule_types.go
  apis/compute/v1beta1/zz_projectmetadataitem_types.go
  apis/notebooks/v1beta1/zz_runtime_types.go
  config/compute/config.go
  config/notebooks/config.go
  package/crds/compute.gcp.upbound.io_firewallpolicyrules.yaml
  package/crds/compute.gcp.upbound.io_projectmetadataitems.yaml
  package/crds/notebooks.gcp.upbound.io_runtimes.yaml
Labels: size/M
