Repository crossplane-contrib/provider-upjet-gcp, pull requests merged in 2022-11, with the labels that each got.

#43 Fix agent used in Dockerfile
  cluster/images/provider-gcp/Dockerfile
Labels: size/XS

#46 Fix secret selector of google_secret_manager_secret_version
  apis/secretmanager/v1beta1/zz_generated.resolvers.go
  apis/secretmanager/v1beta1/zz_secretversion_types.go
  config/secretmanager/config.go
Labels: size/XS

#50 Fix Uptest timeout annotation
  examples/compute/network.yaml
Labels: size/XS

#48 Configurable maxConcurrentReconciles and pollInterval with sensible defaults
  cmd/provider/main.go
Labels: size/S

#52 Remove Terraform-specific comments from secretmanager.SecretVersion's SecretDataSecretRef field
  apis/secretmanager/v1beta1/zz_secretversion_types.go
  config/secretmanager/config.go
  package/crds/secretmanager.gcp.upbound.io_secretversions.yaml
Labels: size/XS

#54 Use self-link for Cluster network/subnetwork selector
  apis/container/v1beta1/zz_cluster_types.go
  apis/container/v1beta1/zz_generated.resolvers.go
  config/container/config.go
Labels: size/XS, community
